<a href="https://colab.research.google.com/github/shivam-bajaj/TensorFlow/blob/master/00_tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow**

## **Intro to Tensors**

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

### *`tf.constant`*

In [3]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const')>

In [4]:
# create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check dimension of a tensor
# tenosr rank 1
scalar.ndim

0

In [6]:
# create a vector
# tensor rank 1
vector = tf.constant([7,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# create a matrix
# tensor rank -2
matrix = tf.constant([[7,10],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# another matrix with specific data type
another_matrix = tf.constant([[1.,2.],[3.,4]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [11]:
# tensor rank 2
another_matrix.ndim

2

In [12]:
# tensor rank -3
tensor = tf.constant([[[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [4, 5]],

       [[4, 5],
        [5, 6]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
tensor2 = tf.constant([[
                      [[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]],
                      [[[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]]])
tensor2

<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [3, 4]],

        [[3, 4],
         [4, 5]],

        [[4, 5],
         [5, 6]]],


       [[[1, 2],
         [3, 4]],

        [[3, 4],
         [4, 5]],

        [[4, 5],
         [5, 6]]]], dtype=int32)>

In [15]:
tensor2.ndim

4



 &emsp;&emsp; **Tensors**  &emsp;&&emsp;&emsp; **Rank**

*   scalar &emsp;&emsp;&emsp; ----->    Rank 0 tensor
*   vector &emsp;&emsp;&emsp; ----->    Rank 1 tensor
*   matrix &emsp;&emsp;&emsp; ----->    Rank 2 tensor
*   another_matrix----->    Rank 2 tensor
*   tensor&emsp;&emsp;&emsp;        ----->    Rank 3 tenosr
*   tenosr2  &emsp;&emsp;&emsp;     ----->    Rank 4 tenosr


### *`tf.Variable`*

In [16]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [17]:
variable_tensor= tf.Variable([7,10])
constant_tensor = tf.constant([7,10])
variable_tensor,constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [18]:
# changing the value in tensor
variable_tensor[1].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
#changing the value in constant_tensor
constant_tensor[1].assign(7)

AttributeError: ignored

In [20]:
constant_tensor[1]=7

TypeError: ignored


```
All eager tf.Tensor values are immutable (in contrast to tf.Variable).
```

### *`tf.ones`*
> Creates a tensor with all elements set to one (1).

In [21]:
one = tf.ones(shape=(3,2,2))
one

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

### *`tf.zeros`*
> Creates a tensor with all elements set to zero.

In [22]:
zeros = tf.zeros(shape=(2,3,4))
zeros

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### **Random Tensors**

#### *`tf.random.Generator`*
Random-number generator

In [23]:
#create 2 random tensors (equal) , setting seed for reproducabilty
ran_1 = tf.random.Generator.from_seed(seed=42)
ran_2 = tf.random.Generator.from_seed(seed=42)

#### *`tf.random.normal`*
Outputs random values from a normal distribution.

In [24]:
random_1 = ran_1.normal(shape=(3,2))
random_2 = ran_2.normal(shape=(3,2))
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

#### *`tf.random.uniform`*
Outputs random values from a uniform distribution.


In [25]:
random_3 = ran_1.uniform(shape=(3,2))
random_4 = ran_2.uniform(shape=(3,2))
random_3,random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7647915 , 0.03845465],
        [0.8506975 , 0.20781887],
        [0.711869  , 0.8843919 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7647915 , 0.03845465],
        [0.8506975 , 0.20781887],
        [0.711869  , 0.8843919 ]], dtype=float32)>)

In [26]:
'''
random_5 has diiferent value even though we have set the same seed or if we
re-run, we will get the different output
'''
#because it is operation-level seed.
random_5 = tf.random.uniform(shape=(3,2),seed=42)
random_5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.95227146, 0.67740774],
       [0.79531825, 0.75578177],
       [0.4759556 , 0.6310148 ]], dtype=float32)>

### **`tf.random.set_seed`**
> Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.


```
#operational-level seed
random_5 = tf.random.uniform(shape=(3,2),seed=7)
```


```
# global level seed
tf.random.set_seed(1234)
```




- If the global seed is set but the operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run of the program:

In [27]:
# gloabl seed
tf.random.set_seed(42)
random_6 = tf.random.uniform(shape=(3,2))
random_7 = tf.random.uniform(shape=(3,2))
random_6,random_7

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678],
        [0.3528825 , 0.46448255],
        [0.03366041, 0.68467236]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.68789124, 0.48447883],
        [0.9309944 , 0.252187  ],
        [0.73115396, 0.89256823]], dtype=float32)>)

- If the operation seed is set, we get different results for
every call to the random op, but the same sequence for every re-run of the program:

In [28]:
random_6 = tf.random.uniform(shape=(3,2),seed=1)
random_7 = tf.random.uniform(shape=(3,2),seed=1)
random_6,random_7

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.15012848, 0.63992536],
        [0.81787777, 0.34572172],
        [0.99661934, 0.64152765]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.01177216, 0.02529657],
        [0.06012475, 0.5448892 ],
        [0.3730942 , 0.6073855 ]], dtype=float32)>)

Differnt output on the second call of `tf.random.uniform` above is because the same tf.random.uniform kernel (i.e. internal representation) is used by TensorFlow for all calls of it with the same arguments, and the kernel maintains an internal counter which is incremented every time it is executed, generating different results.

Calling `tf.random.set_seed` will reset any such counters:

In [29]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


### **`tf.random.shuffle`**
>Randomly shuffles a tensor along its first dimension.




In [30]:
# Shuffle the tensor ( valuable when you want to shuffle the data so inherent doesn't affect learning)
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [4,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

In [31]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [3, 4]], dtype=int32)>

In [32]:
# for reprducability
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled,seed=10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [3, 4]], dtype=int32)>

### **Tensors from NumPy arrays**

In [33]:
import numpy as np
numpy_A= np.arange(0,24)
numpy_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
c = tf.constant(numpy_A,shape=(2,3,4))
c

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

## *Tensor Attributes*

> getting information from tensors
- Shape
- Rank
- Axis or dimension
- Size


In [45]:
tf.random.set_seed(42)
t = tf.random.uniform(shape=(2,3,4,5),maxval=200,seed=42,dtype=tf.int32)
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[ 33, 138, 130, 174, 108],
         [141, 153,  73,  42,   5],
         [176, 144,  93, 167,   6],
         [166,  42,  43, 191,  18]],

        [[ 46, 190,  14, 176,  91],
         [ 91, 146, 169,  72,  85],
         [100, 154, 174,  78, 168],
         [134, 164, 141, 150, 171]],

        [[ 87, 116, 100, 166, 197],
         [150, 167,  12, 156, 142],
         [111, 165, 129,  79, 199],
         [ 66,  14,  81, 159, 144]]],


       [[[161,   4,  12,  43,  53],
         [  6,  89,  35,  40,  18],
         [187,  74, 102, 198, 102],
         [ 16, 173,  26, 155, 162]],

        [[150, 164, 107,  38, 154],
         [124,  16, 199, 106,   4],
         [ 94,   8, 151, 132, 175],
         [ 19,  17,  34, 180, 198]],

        [[183, 185, 141,  83,  41],
         [147,  98, 133,  49, 193],
         [118,  68, 168,  15,  41],
         [154, 130,  10, 138,  57]]]], dtype=int32)>

In [46]:
t[1][2][3][4]

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [47]:
# shape of tensor
t.shape

TensorShape([2, 3, 4, 5])

In [48]:
# rank of tensor
t.ndim

4

In [50]:
# size of elements
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [56]:
tf.size(t).numpy()

120

In [57]:
# Elements along 0 axis
t.shape[0]

2

In [58]:
# last axis
t.shape[-1]

5

In [59]:
# dtype
t.dtype

tf.int32