<a href="https://colab.research.google.com/github/shivam-bajaj/TensorFlow/blob/master/00_tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TensorFlow**

## **Intro to Tensors**

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.12.0'

### *`tf.constant`*

In [3]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const')>

In [4]:
# create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check dimension of a tensor
# tenosr rank 1
scalar.ndim

0

In [6]:
# create a vector
# tensor rank 1
vector = tf.constant([7,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
# create a matrix
# tensor rank -2
matrix = tf.constant([[7,10],[10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
# another matrix with specific data type
another_matrix = tf.constant([[1.,2.],[3.,4]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

In [11]:
# tensor rank 2
another_matrix.ndim

2

In [12]:
# tensor rank -3
tensor = tf.constant([[[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]])
tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [4, 5]],

       [[4, 5],
        [5, 6]]], dtype=int32)>

In [13]:
tensor.ndim

3

In [14]:
tensor2 = tf.constant([[
                      [[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]],
                      [[[1,2],[3,4]],
                      [[3,4],[4,5]],
                      [[4,5],[5,6]]]])
tensor2

<tf.Tensor: shape=(2, 3, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [3, 4]],

        [[3, 4],
         [4, 5]],

        [[4, 5],
         [5, 6]]],


       [[[1, 2],
         [3, 4]],

        [[3, 4],
         [4, 5]],

        [[4, 5],
         [5, 6]]]], dtype=int32)>

In [15]:
tensor2.ndim

4



 &emsp;&emsp; **Tensors**  &emsp;&&emsp;&emsp; **Rank**

*   scalar &emsp;&emsp;&emsp; ----->    Rank 0 tensor
*   vector &emsp;&emsp;&emsp; ----->    Rank 1 tensor
*   matrix &emsp;&emsp;&emsp; ----->    Rank 2 tensor
*   another_matrix----->    Rank 2 tensor
*   tensor&emsp;&emsp;&emsp;        ----->    Rank 3 tenosr
*   tenosr2  &emsp;&emsp;&emsp;     ----->    Rank 4 tenosr


### *`tf.Variable`*

In [16]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [17]:
variable_tensor= tf.Variable([7,10])
constant_tensor = tf.constant([7,10])
variable_tensor,constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [18]:
# changing the value in tensor
variable_tensor[1].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [19]:
#changing the value in constant_tensor
constant_tensor[1].assign(7)

AttributeError: ignored

In [20]:
constant_tensor[1]=7

TypeError: ignored


```
All eager tf.Tensor values are immutable (in contrast to tf.Variable).
```

### *`tf.ones`*
> Creates a tensor with all elements set to one (1).

In [21]:
one = tf.ones(shape=(3,2,2))
one

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

### *`tf.zeros`*
> Creates a tensor with all elements set to zero.

In [22]:
zeros = tf.zeros(shape=(2,3,4))
zeros

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float32)>

### **Random Tensors**

#### *`tf.random.Generator`*
Random-number generator

In [23]:
#create 2 random tensors (equal) , setting seed for reproducabilty
ran_1 = tf.random.Generator.from_seed(seed=42)
ran_2 = tf.random.Generator.from_seed(seed=42)

#### *`tf.random.normal`*
Outputs random values from a normal distribution.

In [24]:
random_1 = ran_1.normal(shape=(3,2))
random_2 = ran_2.normal(shape=(3,2))
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

#### *`tf.random.uniform`*
Outputs random values from a uniform distribution.


In [25]:
random_3 = ran_1.uniform(shape=(3,2))
random_4 = ran_2.uniform(shape=(3,2))
random_3,random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7647915 , 0.03845465],
        [0.8506975 , 0.20781887],
        [0.711869  , 0.8843919 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7647915 , 0.03845465],
        [0.8506975 , 0.20781887],
        [0.711869  , 0.8843919 ]], dtype=float32)>)

In [26]:
'''
random_5 has diiferent value even though we have set the same seed or if we
re-run, we will get the different output
'''
#because it is operation-level seed.
random_5 = tf.random.uniform(shape=(3,2),seed=42)
random_5

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.95227146, 0.67740774],
       [0.79531825, 0.75578177],
       [0.4759556 , 0.6310148 ]], dtype=float32)>

### **`tf.random.set_seed`**
> Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed.


```
#operational-level seed
random_5 = tf.random.uniform(shape=(3,2),seed=7)
```


```
# global level seed
tf.random.set_seed(1234)
```




- If the global seed is set but the operation seed is not set, we get different results for every call to the random op, but the same sequence for every re-run of the program:

In [27]:
# gloabl seed
tf.random.set_seed(42)
random_6 = tf.random.uniform(shape=(3,2))
random_7 = tf.random.uniform(shape=(3,2))
random_6,random_7

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678],
        [0.3528825 , 0.46448255],
        [0.03366041, 0.68467236]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.68789124, 0.48447883],
        [0.9309944 , 0.252187  ],
        [0.73115396, 0.89256823]], dtype=float32)>)

- If the operation seed is set, we get different results for
every call to the random op, but the same sequence for every re-run of the program:

In [28]:
random_6 = tf.random.uniform(shape=(3,2),seed=1)
random_7 = tf.random.uniform(shape=(3,2),seed=1)
random_6,random_7

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.15012848, 0.63992536],
        [0.81787777, 0.34572172],
        [0.99661934, 0.64152765]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.01177216, 0.02529657],
        [0.06012475, 0.5448892 ],
        [0.3730942 , 0.6073855 ]], dtype=float32)>)

Differnt output on the second call of `tf.random.uniform` above is because the same tf.random.uniform kernel (i.e. internal representation) is used by TensorFlow for all calls of it with the same arguments, and the kernel maintains an internal counter which is incremented every time it is executed, generating different results.

Calling `tf.random.set_seed` will reset any such counters:

In [29]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


### **`tf.random.shuffle`**
>Randomly shuffles a tensor along its first dimension.




In [30]:
# Shuffle the tensor ( valuable when you want to shuffle the data so inherent doesn't affect learning)
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [4,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]], dtype=int32)>

In [31]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [3, 4]], dtype=int32)>

In [32]:
# for reprducability
tf.random.set_seed(7)
tf.random.shuffle(not_shuffled,seed=10)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [3, 4]], dtype=int32)>

### **Tensors from NumPy arrays**

In [33]:
import numpy as np
numpy_A= np.arange(0,24)
numpy_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
c = tf.constant(numpy_A,shape=(2,3,4))
c

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])>

## *Tensor Attributes*

> getting information from tensors
- Shape
- Rank
- Axis or dimension
- Size


In [35]:
tf.random.set_seed(42)
t = tf.random.uniform(shape=(2,3,4,5),maxval=200,seed=42,dtype=tf.int32)
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[ 33, 138, 130, 174, 108],
         [141, 153,  73,  42,   5],
         [176, 144,  93, 167,   6],
         [166,  42,  43, 191,  18]],

        [[ 46, 190,  14, 176,  91],
         [ 91, 146, 169,  72,  85],
         [100, 154, 174,  78, 168],
         [134, 164, 141, 150, 171]],

        [[ 87, 116, 100, 166, 197],
         [150, 167,  12, 156, 142],
         [111, 165, 129,  79, 199],
         [ 66,  14,  81, 159, 144]]],


       [[[161,   4,  12,  43,  53],
         [  6,  89,  35,  40,  18],
         [187,  74, 102, 198, 102],
         [ 16, 173,  26, 155, 162]],

        [[150, 164, 107,  38, 154],
         [124,  16, 199, 106,   4],
         [ 94,   8, 151, 132, 175],
         [ 19,  17,  34, 180, 198]],

        [[183, 185, 141,  83,  41],
         [147,  98, 133,  49, 193],
         [118,  68, 168,  15,  41],
         [154, 130,  10, 138,  57]]]], dtype=int32)>

In [36]:
t[1][2][3][4]

<tf.Tensor: shape=(), dtype=int32, numpy=57>

In [37]:
# shape of tensor
t.shape

TensorShape([2, 3, 4, 5])

In [38]:
# rank of tensor
t.ndim

4

In [39]:
# size of elements
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [40]:
tf.size(t).numpy()

120

In [41]:
# Elements along 0 axis
t.shape[0]

2

In [42]:
# last axis
t.shape[-1]

5

In [43]:
# dtype
t.dtype

tf.int32

## **Indexing Tensors**

In [44]:
t

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[ 33, 138, 130, 174, 108],
         [141, 153,  73,  42,   5],
         [176, 144,  93, 167,   6],
         [166,  42,  43, 191,  18]],

        [[ 46, 190,  14, 176,  91],
         [ 91, 146, 169,  72,  85],
         [100, 154, 174,  78, 168],
         [134, 164, 141, 150, 171]],

        [[ 87, 116, 100, 166, 197],
         [150, 167,  12, 156, 142],
         [111, 165, 129,  79, 199],
         [ 66,  14,  81, 159, 144]]],


       [[[161,   4,  12,  43,  53],
         [  6,  89,  35,  40,  18],
         [187,  74, 102, 198, 102],
         [ 16, 173,  26, 155, 162]],

        [[150, 164, 107,  38, 154],
         [124,  16, 199, 106,   4],
         [ 94,   8, 151, 132, 175],
         [ 19,  17,  34, 180, 198]],

        [[183, 185, 141,  83,  41],
         [147,  98, 133,  49, 193],
         [118,  68, 168,  15,  41],
         [154, 130,  10, 138,  57]]]], dtype=int32)>

Get the first element

In [45]:
t[0,0,0,0],t[0][0][0][0]

(<tf.Tensor: shape=(), dtype=int32, numpy=33>,
 <tf.Tensor: shape=(), dtype=int32, numpy=33>)

 Get the last element

In [46]:
t[-1,-1,-1,-1],t[-1,-1,-1,-1]

(<tf.Tensor: shape=(), dtype=int32, numpy=57>,
 <tf.Tensor: shape=(), dtype=int32, numpy=57>)

Get the first 2 elements of each dimension

In [47]:
t[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[ 33, 138],
         [141, 153]],

        [[ 46, 190],
         [ 91, 146]]],


       [[[161,   4],
         [  6,  89]],

        [[150, 164],
         [124,  16]]]], dtype=int32)>

In [48]:
#Get the first element from each dimension from each index except for final one
t[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[ 33, 138, 130, 174, 108]]]], dtype=int32)>

## **Reshaping Tensors**
### `tf.reshape`

In [49]:
tf.shape(t).numpy()

array([2, 3, 4, 5], dtype=int32)

In [50]:
2*3*4*5

120

In [51]:
tf.reshape(t,(3,2,5,4))

<tf.Tensor: shape=(3, 2, 5, 4), dtype=int32, numpy=
array([[[[ 33, 138, 130, 174],
         [108, 141, 153,  73],
         [ 42,   5, 176, 144],
         [ 93, 167,   6, 166],
         [ 42,  43, 191,  18]],

        [[ 46, 190,  14, 176],
         [ 91,  91, 146, 169],
         [ 72,  85, 100, 154],
         [174,  78, 168, 134],
         [164, 141, 150, 171]]],


       [[[ 87, 116, 100, 166],
         [197, 150, 167,  12],
         [156, 142, 111, 165],
         [129,  79, 199,  66],
         [ 14,  81, 159, 144]],

        [[161,   4,  12,  43],
         [ 53,   6,  89,  35],
         [ 40,  18, 187,  74],
         [102, 198, 102,  16],
         [173,  26, 155, 162]]],


       [[[150, 164, 107,  38],
         [154, 124,  16, 199],
         [106,   4,  94,   8],
         [151, 132, 175,  19],
         [ 17,  34, 180, 198]],

        [[183, 185, 141,  83],
         [ 41, 147,  98, 133],
         [ 49, 193, 118,  68],
         [168,  15,  41, 154],
         [130,  10, 138,  57]]]], d

## Expanding the Tensors

In [52]:
t_rank2= tf.constant([10,7,9,5],shape=(2,2))
t_rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 9,  5]], dtype=int32)>

### `tf.newaxis`

In [53]:
# Add in extra dimension
#t_rank3 = t_rank2[:,:,tf.newaxis]
t_rank3 = t_rank2[[... , tf.newaxis]]
t_rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 9],
        [ 5]]], dtype=int32)>

In [54]:
t_rank3 = t_rank2[tf.newaxis,:,:]
t_rank3

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 9,  5]]], dtype=int32)>

### `tf.expand_dims`

In [55]:
tf.expand_dims(t_rank2,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 9],
        [ 5]]], dtype=int32)>

In [56]:
tf.expand_dims(t_rank2,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 9,  5]]], dtype=int32)>

## Manipulating Tensors (Tensor Operations)

#### Basic Operations
`+,-,*,/`

In [57]:
tensor = tf.constant([10,7,1,2],shape=(2,2))
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2]], dtype=int32)>

In [58]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [11, 12]], dtype=int32)>

In [59]:
tensor-7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  0],
       [-6, -5]], dtype=int32)>

In [60]:
tensor*2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 2,  4]], dtype=int32)>

#### `tf.math`
Tensor built-in functions to perform.(preferred way)

In [61]:
tf.math.multiply(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 2,  4]], dtype=int32)>

In [62]:
tf.math.argmax(tensor)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

### Matrix Multiplication
- `tf.linalg.matmul`
- `@`
- `tf.tensordot`

In [63]:
tf.random.set_seed(42)
x=tf.random.uniform(shape=(3,2),dtype=tf.int32,maxval=20,seed=42)
y=tf.random.uniform(shape=(2,3),dtype=tf.int32,maxval=20,seed=42)

#### `tf.linalg.matmul`
Multiplies matrix a by matrix b, producing a * b.

In [64]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[107,  84],
       [ 12,  11]], dtype=int32)>

In [65]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[288, 179, 199],
       [224, 138, 154],
       [ 16,  90,  62]], dtype=int32)>

#### `'@'` operator python matrix multiplication

In [66]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[107,  84],
       [ 12,  11]], dtype=int32)>

In [67]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[288, 179, 199],
       [224, 138, 154],
       [ 16,  90,  62]], dtype=int32)>

#### `tf.tensordot`
Tensor contraction of a and b along specified axes and outer product.

In [68]:
a = tf.constant([1,2,3,4],shape=(2,2))
b = tf.ones(shape=(2,2),dtype=tf.int32)

In [69]:
# performs matrix-multiplication
tf.tensordot(a,b,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [70]:
# One by one each element(scalar) of first matrix multiply with all element of second matrix
# and keeps output in separate matrix for each element multiplication.
tf.tensordot(a,b,axes=0)

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 4]]]], dtype=int32)>

In [71]:
# performs element-wise multiplication,sums the result into scalar.
tf.tensordot(a,b,axes=2)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

### `tf.transpose`

In [72]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[13, 18],
       [10, 14],
       [ 8,  1]], dtype=int32)>

In [73]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 10,  8],
       [18, 14,  1]], dtype=int32)>

In [74]:
tf.reshape(x,(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 18, 10],
       [14,  8,  1]], dtype=int32)>

`transponse` flips the axis, while `reshape` changes the shape with particular order

### Change the datatype of tensor

In [75]:
t1 = tf.constant([1.7,0.9])
t1.dtype

tf.float32

#### `tf.cast`

In [76]:
# changing from float32 to float16 (reduced percision)
t2 = tf.cast(t1,dtype=tf.float16)
t2

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 0.9], dtype=float16)>

In [77]:
t3 = tf.cast(t1,dtype= tf.int16)
t3

<tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 0], dtype=int16)>

### Aggregating Tensors

In [78]:
import numpy as np
t = tf.constant(np.random.rand(2,3,2))
a = tf.constant([-1,-4])
a

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-1, -4], dtype=int32)>

#### `tf.abs`
Get the absolute values

In [79]:
tf.abs(a)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

#### `tf.reduce_min`
Find the minimum

In [80]:
t

<tf.Tensor: shape=(2, 3, 2), dtype=float64, numpy=
array([[[0.12808268, 0.68219421],
        [0.11227912, 0.97035033],
        [0.45517014, 0.4717848 ]],

       [[0.54932319, 0.51538728],
        [0.25927842, 0.59493662],
        [0.55088109, 0.52462205]]])>

In [81]:
tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=float64, numpy=0.11227912399579232>

#### `tf.reduce_max`
Find the max.

In [82]:
tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9703503346027572>

#### `tf.reduce_mean`

In [83]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float64, numpy=0.4845241613046046>

#### `tf.reduce_sum`

In [84]:
tf.reduce_sum(t)

<tf.Tensor: shape=(), dtype=float64, numpy=5.814289935655255>

#### `tf.math.reduce_variance`

In [85]:
import tensorflow_probability as tfp
tfp.stats.variance(t)
tf.math.reduce_variance(t)

<tf.Tensor: shape=(), dtype=float64, numpy=0.05131920354750815>

#### `tf.math.reduce_std`



In [86]:
tf.math.reduce_std(t)

<tf.Tensor: shape=(), dtype=float64, numpy=0.2265374219582896>

### Finding the positional Max and Min

In [87]:
tf.random.set_seed(42)
t = tf.random.uniform(shape=[50])
t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#### `tf.argmax`

In [88]:
tf.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [89]:
tf.reduce_max(t) == t[tf.argmax(t)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

#### `tf.argmin`

In [90]:
tf.argmin(t)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [91]:
t[tf.argmin(t)]==tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing the tensor
(removing all single dimensions)

In [92]:
tf.random.set_seed(42)
t = tf.random.uniform(shape=(1,2,1,50))
t

<tf.Tensor: shape=(1, 2, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],

        [[0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
          0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
          0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
          0.18282163, 0.13179815

#### `tf.squeeze`

In [93]:
tf.squeeze(t)

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       [0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
        0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ,
        0.28128064, 0.31513572, 0.60670924, 0.7498598 , 0.5016055 ,
        0.18282163, 0.13179815, 0.64636123, 0.9559475 , 0.6670735 

## One Hot Encoding tensors

In [94]:
some_list =[1,2,3]
tf.one_hot(some_list,depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [95]:
tf.one_hot(some_list,depth=3,on_value="yo",off_value="_")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'_', b'yo', b'_'],
       [b'_', b'_', b'yo'],
       [b'_', b'_', b'_']], dtype=object)>

## Tensors and NumPy

In [96]:
import numpy as np
np_array =[1.,2,3.2]
numpy_t = tf.constant(np_array)
numpy_t

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.2], dtype=float32)>

In [97]:
# convert tensor to numpy
numpy_t.numpy(),np.array(numpy_t)

(array([1. , 2. , 3.2], dtype=float32), array([1. , 2. , 3.2], dtype=float32))

## Access to GPUs

In [100]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [3]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [4]:
!nvidia-smi

Mon Sep  4 15:13:54 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   41C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------